config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :pictures do
    collection do
      put :presign_upload
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/all', to: 'pictures#all_pictures'
  get 'category/:category', to: 'pictures#category'
  root to: 'pictures#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pictures, :dependent => :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy, :remove_image]
  # before_action :set_category, only: [:category]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all.includes(:category)
    respond_to do |format|
        format.html
        format.json
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end

  def all_pictures
    @pictures = Picture.all
    respond_to do |format|
      format.json {render :all_pictures}
    end
  end

  def category
    @pictures = Picture.where(category: params[:category])
    respond_to do |format|
      format.html {render :index}
      format.json {render :category}
    end
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # def set_category
    #   @picture = Picture.where(:category => params[:category])
    # end
    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :category_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
    <br/>
  <div class="actions">
    <%= f.submit :class => 'waves-effect waves-light btn'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= link_to 'View', @category, :class => 'waves-effect waves-light btn' %>
<%= link_to 'Back', categories_path, :class => 'waves-effect waves-light btn' %>
<br/>
<br/>
<br/>
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<div class="row">
  <div class="col s12">
    <p id="notice"><%= notice %></p>

<h1 class="col s12 m6">Categories</h1>
    <%= link_to(new_category_path,
                class: 'btn-floating btn-large waves-effect waves-light red right index-add') do %>
        <i class="material-icons">add</i>
        <!--<a class="waves-effect waves-light btn" href="#add-modal">Modal-->
        <!--<i class="large material-icons">mode_edit</i>-->
        <!--</a>-->
    <% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'View', category, :class => 'waves-effect waves-light btn' %></td>
        <td><%= link_to 'Edit', edit_category_path(category), :class => 'waves-effect waves-light btn' %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'waves-effect waves-light btn' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= link_to 'Back', categories_path, :class => 'waves-effect waves-light btn' %>
<br/>
<br/>
<br/>

<%= render 'form', category: @category %>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<br/>
  <h1><%= @category.name %></h1>

<%= link_to 'Edit', edit_category_path(@category), :class => 'waves-effect waves-light btn' %>
<%= link_to 'Back', categories_path, :class => 'waves-effect waves-light btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P2source</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar-fixed">
    <nav>
      <div class="container">
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Photo Server</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="/pictures">Pictures</a></li>
          <li><a href="/categories">Categories</a></li>
        </ul>
      </div>
      </div>
    </nav>
  </div>
  <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="row"> <%= form_for picture, :html => {:multipart => true} do |f| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row col m12">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="row input-field col m12">
    <%= f.collection_select :category_id, Category.order(:name), :id ,:name, :include_blank => false %>
    <%= f.label :category %>
  </div>

  <div class="row col m12">
    <%= f.label :image %>
    <div class="file-field input-field">
      <div class="btn">
        <span>File</span>
        <%= f.file_field :image, :class => 'hidden-image-input'%>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

    <% if f.object.image? %>
        <div class="card">
          <div class="card-image">
            <%= image_tag f.object.image.url, :class => '' %>
            <span class="card-title"><%=f.object.image.url %></span>
          </div>
        </div>
        <%= f.check_box :remove_image, :class => 'filled-in'%>
        <%= f.label :remove_image %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit :class => 'waves-effect waves-light btn'%>
  </div>
<% end %>
</div>

app/views/pictures/_new_modal.html.erb
<div id="add-modal" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Add New Picture</h4>
    <%= form_for new_picture do |f| %>
            <% if picture.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

                  <ul>
                    <% picture.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="field">
              <%= f.label :name %>
              <%= f.text_field :name %>
            </div>

            <div class="field">
              <%= f.label :category %>
              <%= f.collection_select :category_id, Category.order(:name), :id, :name, :include_blank => false %>

            </div>

            <div class="field">
              <%= f.label :image %>
              <%= f.file_field :image %>
              <% if f.object.image? %>
                  <%= image_tag f.object.image.thumb.url %>
                  <%= f.label :remove_image %>
                  <%= f.check_box :remove_image %>
              <% end %>
            </div>

            <div class="actions">
              <%= f.submit %>
            </div>
        <% end %>
        </div>
        <div class="modal-footer">
          <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat "><%= f.submit %></a>
        </div>
        </div>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="row">
  <div class="col s12">
    <p id="notice"><%= notice %></p>

    <div class="row">
      <h1 class="col s12 m6">Pictures</h1>
      <%= link_to(new_picture_path,
                  class: 'btn-floating btn-large waves-effect waves-light red right index-add') do %>
          <i class="material-icons">add</i>
          <!--<a class="waves-effect waves-light btn" href="#add-modal">Modal-->
          <!--<i class="large material-icons">mode_edit</i>-->
          <!--</a>-->
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <% @pictures.each do |picture| %>

      <div class="col s6 m4">
        <div class="card">
          <div class="card-image index-card-image">
            <%= image_tag picture.image.url %>
            <span class="card-title"><%= picture.name %></span>
          </div>
          <div class="card-content">
            <p class="category"><strong>Category: </strong><%= picture.category.name %></p>
          </div>
          <div class="card-action">
            <%= link_to 'View', picture %>
            <%= link_to 'Edit', edit_picture_path(picture) %>
            <%= link_to 'Delete', picture, method: :delete, data: {confirm: 'Are you sure?'} %>
          </div>
        </div>
      </div>
  <% end %>
</div>

<script>
    $(document).ready(function(){
        // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
        $('.modal').modal();
    });
</script>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>

app/views/pictures/show.html.erb
<br>
<%= link_to 'Edit', edit_picture_path(@picture), :class => 'waves-effect waves-light btn' %>
<%= link_to 'Back', pictures_path, :class => 'waves-effect waves-light btn' %>
<div class="row">
  <p id="notice"><%= notice %></p>
</div>
<div class="row">
  <div class="col m12">
    <div class="card">
      <div class="card-content">
        <p><%= @picture.name %></p>
        <p class="category"><strong>Category: </strong><%= @picture.category.name %></p>
      </div>
      <div class="card-image">
        <span class="card-title"><%= @picture.name %></span>
        <%= image_tag(@picture.image.url, :class => "thumb") %>
      </div>
    </div>
  </div>
</div>